"""initial schema

Revision ID: e15f9e1f2f04
Revises:
Create Date: 2026-09-07 21:48:17.967063
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "e15f9e1f2f04"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alerts",
        sa.Column("scope", sa.String(length=128), nullable=False),
        sa.Column("rule_id", sa.String(length=64), nullable=False),
        sa.Column("episode_key", sa.String(length=128), nullable=False),
        sa.Column("dedupe_key", sa.String(length=300), nullable=False),
        sa.Column("severity", sa.String(length=8), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("consecutive_reads", sa.Integer(), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_notified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("recovered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "dedupe_key", name="uq_alerts_dedupe"),
    )
    op.create_index(op.f("ix_alerts_tenant_id"), "alerts", ["tenant_id"], unique=False)
    op.create_table(
        "audit_events",
        sa.Column("actor", sa.String(length=120), nullable=False),
        sa.Column("operation", sa.String(length=64), nullable=False),
        sa.Column("object_type", sa.String(length=64), nullable=False),
        sa.Column("object_id", sa.String(length=128), nullable=False),
        sa.Column("before_hash", sa.String(length=64), nullable=True),
        sa.Column("after_hash", sa.String(length=64), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("correlation_id", sa.String(length=64), nullable=False),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_events_tenant_id"), "audit_events", ["tenant_id"], unique=False)
    op.create_table(
        "cohort_metrics",
        sa.Column("scope", sa.String(length=16), nullable=False),
        sa.Column("entity_key", sa.String(length=128), nullable=False),
        sa.Column("cohort_date", sa.Date(), nullable=False),
        sa.Column("as_of", sa.DateTime(timezone=True), nullable=False),
        sa.Column("age_days", sa.Integer(), nullable=False),
        sa.Column("orders", sa.Integer(), nullable=False),
        sa.Column("ordered_revenue", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("expected_revenue", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("expected_costs", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("expected_contribution", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("expected_low", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("expected_high", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("realized_revenue", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("realized_costs", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("realized_contribution", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("ad_spend", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("uncertainty", sa.String(length=16), nullable=False),
        sa.Column("model_version", sa.String(length=16), nullable=False),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id", "scope", "entity_key", "cohort_date", "as_of", name="uq_cohort_metrics"
        ),
    )
    op.create_index(op.f("ix_cohort_metrics_cohort_date"), "cohort_metrics", ["cohort_date"], unique=False)
    op.create_index(op.f("ix_cohort_metrics_tenant_id"), "cohort_metrics", ["tenant_id"], unique=False)
    op.create_table(
        "connector_capabilities",
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("tool_name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("input_schema", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("schema_hash", sa.String(length=64), nullable=False),
        sa.Column("read_only_hint", sa.Boolean(), nullable=True),
        sa.Column("discovered_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "source", "tool_name", "schema_hash", name="uq_connector_caps"),
    )
    op.create_index(
        op.f("ix_connector_capabilities_tenant_id"), "connector_capabilities", ["tenant_id"], unique=False
    )
    op.create_table(
        "daily_metrics",
        sa.Column("scope", sa.String(length=16), nullable=False),
        sa.Column("entity_key", sa.String(length=128), nullable=False),
        sa.Column("business_date", sa.Date(), nullable=False),
        sa.Column("metric", sa.String(length=64), nullable=False),
        sa.Column("metric_version", sa.String(length=16), nullable=False),
        sa.Column("as_of", sa.DateTime(timezone=True), nullable=False),
        sa.Column("numerator", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("denominator", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("value", sa.Numeric(precision=24, scale=8), nullable=True),
        sa.Column("reason", sa.String(length=64), nullable=True),
        sa.Column("quality", sa.String(length=16), nullable=False),
        sa.Column("evidence_id", sa.String(length=160), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id",
            "scope",
            "entity_key",
            "business_date",
            "metric",
            "metric_version",
            "as_of",
            name="uq_daily_metrics",
        ),
    )
    op.create_index(
        "ix_daily_metrics_lookup",
        "daily_metrics",
        ["scope", "entity_key", "metric", "business_date"],
        unique=False,
    )
    op.create_index(op.f("ix_daily_metrics_tenant_id"), "daily_metrics", ["tenant_id"], unique=False)
    op.create_table(
        "data_quality_issues",
        sa.Column("scope", sa.String(length=128), nullable=False),
        sa.Column("check_name", sa.String(length=64), nullable=False),
        sa.Column("expected", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("actual", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("severity", sa.String(length=8), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("business_date", sa.Date(), nullable=True),
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("dedupe_key", sa.String(length=200), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_data_quality_issues_dedupe_key"), "data_quality_issues", ["dedupe_key"], unique=False
    )
    op.create_index(
        op.f("ix_data_quality_issues_tenant_id"), "data_quality_issues", ["tenant_id"], unique=False
    )
    op.create_table(
        "job_runs",
        sa.Column("job_name", sa.String(length=64), nullable=False),
        sa.Column("scheduled_for", sa.DateTime(timezone=True), nullable=False),
        sa.Column("scope", sa.String(length=128), nullable=False),
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("lease_owner", sa.String(length=120), nullable=True),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("timeout_seconds", sa.Integer(), nullable=False),
        sa.Column("records_processed", sa.Integer(), nullable=False),
        sa.Column("checkpoint", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("error_class", sa.String(length=64), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("correlation_id", sa.String(length=64), nullable=False),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "job_name", "scheduled_for", "scope", name="uq_job_runs"),
    )
    op.create_index(op.f("ix_job_runs_job_name"), "job_runs", ["job_name"], unique=False)
    op.create_index(op.f("ix_job_runs_scheduled_for"), "job_runs", ["scheduled_for"], unique=False)
    op.create_index(op.f("ix_job_runs_status"), "job_runs", ["status"], unique=False)
    op.create_index(op.f("ix_job_runs_tenant_id"), "job_runs", ["tenant_id"], unique=False)
    op.create_table(
        "policy_snapshots",
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("config_hash", sa.String(length=64), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("version", sa.String(length=32), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "name", "config_hash", name="uq_policy_snapshots"),
    )
    op.create_index(op.f("ix_policy_snapshots_tenant_id"), "policy_snapshots", ["tenant_id"], unique=False)
    op.create_table(
        "reports",
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("scope", sa.String(length=64), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("revision_reason", sa.Text(), nullable=True),
        sa.Column("as_of", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completeness", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("evidence_bundle", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("body", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("rendered_markdown", sa.Text(), nullable=True),
        sa.Column("rendered_html", sa.Text(), nullable=True),
        sa.Column("model_name", sa.String(length=120), nullable=True),
        sa.Column("prompt_version", sa.String(length=32), nullable=True),
        sa.Column("llm_used", sa.Boolean(), nullable=False),
        sa.Column("llm_error", sa.Text(), nullable=True),
        sa.Column("tokens_in", sa.Integer(), nullable=True),
        sa.Column("tokens_out", sa.Integer(), nullable=True),
        sa.Column("cost_pln", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("missing", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id", "kind", "period_start", "period_end", "scope", "revision", name="uq_reports"
        ),
    )
    op.create_index(op.f("ix_reports_tenant_id"), "reports", ["tenant_id"], unique=False)
    op.create_table(
        "shops",
        sa.Column("shop_key", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("domain", sa.String(length=200), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("order_date_basis", sa.String(length=16), nullable=False),
        sa.Column("tax_basis", sa.String(length=8), nullable=False),
        sa.Column("aliases", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "shop_key", name="uq_shops_tenant_key"),
    )
    op.create_index(op.f("ix_shops_tenant_id"), "shops", ["tenant_id"], unique=False)
    op.create_table(
        "historical_observations",
        sa.Column("shop_id", sa.UUID(), nullable=True),
        sa.Column("observed_at", sa.Date(), nullable=False),
        sa.Column("source_ref", sa.String(length=200), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["shop_id"],
            ["shops.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_historical_observations_tenant_id"), "historical_observations", ["tenant_id"], unique=False
    )
    op.create_table(
        "notification_outbox",
        sa.Column("dedupe_key", sa.String(length=300), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("report_id", sa.UUID(), nullable=True),
        sa.Column("alert_id", sa.UUID(), nullable=True),
        sa.Column("channel", sa.String(length=32), nullable=False),
        sa.Column("subject", sa.String(length=300), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("delivery_id", sa.String(length=200), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["alert_id"],
            ["alerts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["reports.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "dedupe_key", name="uq_notification_outbox"),
    )
    op.create_index(
        op.f("ix_notification_outbox_tenant_id"), "notification_outbox", ["tenant_id"], unique=False
    )
    op.create_table(
        "products",
        sa.Column("shop_id", sa.UUID(), nullable=False),
        sa.Column("product_key", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("product_status", sa.String(length=32), nullable=False),
        sa.Column("attributes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["shop_id"],
            ["shops.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "shop_id", "product_key", name="uq_products_key"),
    )
    op.create_index(op.f("ix_products_tenant_id"), "products", ["tenant_id"], unique=False)
    op.create_table(
        "recommendations",
        sa.Column("report_id", sa.UUID(), nullable=True),
        sa.Column("rule_id", sa.String(length=64), nullable=False),
        sa.Column("rule_version", sa.String(length=16), nullable=False),
        sa.Column("entity_ref", sa.String(length=200), nullable=False),
        sa.Column("business_date", sa.Date(), nullable=False),
        sa.Column("action_type", sa.String(length=32), nullable=False),
        sa.Column("fact", sa.Text(), nullable=False),
        sa.Column("hypothesis", sa.Text(), nullable=False),
        sa.Column("evidence_refs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("priority_class", sa.String(length=16), nullable=False),
        sa.Column("priority_rank", sa.Integer(), nullable=False),
        sa.Column("confidence_class", sa.String(length=8), nullable=False),
        sa.Column("confidence_components", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("evidence_score", sa.Integer(), nullable=True),
        sa.Column("gates", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("blocking_gates", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("impact", sa.String(length=8), nullable=False),
        sa.Column("urgency", sa.String(length=8), nullable=False),
        sa.Column("effort", sa.String(length=8), nullable=False),
        sa.Column("execution_allowed", sa.Boolean(), nullable=False),
        sa.Column("alternative", sa.Text(), nullable=False),
        sa.Column("conditions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("next_check_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["reports.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_recommendations_entity_ref"), "recommendations", ["entity_ref"], unique=False)
    op.create_index(op.f("ix_recommendations_tenant_id"), "recommendations", ["tenant_id"], unique=False)
    op.create_table(
        "source_accounts",
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("external_id", sa.String(length=128), nullable=False),
        sa.Column("shop_id", sa.UUID(), nullable=True),
        sa.Column("display_name", sa.String(length=200), nullable=True),
        sa.Column("timezone", sa.String(length=64), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("config_version", sa.String(length=64), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("mapping_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["shop_id"],
            ["shops.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "source", "external_id", name="uq_source_accounts"),
    )
    op.create_index(op.f("ix_source_accounts_tenant_id"), "source_accounts", ["tenant_id"], unique=False)
    op.create_table(
        "campaigns",
        sa.Column("source_account_id", sa.UUID(), nullable=False),
        sa.Column("external_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("objective", sa.String(length=64), nullable=True),
        sa.Column("configured_status", sa.String(length=32), nullable=True),
        sa.Column("effective_status", sa.String(length=32), nullable=True),
        sa.Column("daily_budget", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("lifetime_budget", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("budget_type", sa.String(length=8), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_account_id"],
            ["source_accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "source_account_id", "external_id", name="uq_campaigns"),
    )
    op.create_index(op.f("ix_campaigns_tenant_id"), "campaigns", ["tenant_id"], unique=False)
    op.create_table(
        "concepts",
        sa.Column("concept_key", sa.String(length=128), nullable=False),
        sa.Column("shop_id", sa.UUID(), nullable=True),
        sa.Column("product_id", sa.UUID(), nullable=True),
        sa.Column("problem_desire", sa.Text(), nullable=False),
        sa.Column("mechanism", sa.Text(), nullable=False),
        sa.Column("narrative", sa.Text(), nullable=False),
        sa.Column("classification_version", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["shop_id"],
            ["shops.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "concept_key", name="uq_concepts"),
    )
    op.create_index(op.f("ix_concepts_tenant_id"), "concepts", ["tenant_id"], unique=False)
    op.create_table(
        "experiments",
        sa.Column("shop_id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=True),
        sa.Column("hypothesis", sa.Text(), nullable=False),
        sa.Column("scope", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("primary_metric", sa.String(length=64), nullable=False),
        sa.Column("budget_pln", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("loss_cap_pln", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("baseline", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("start_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("end_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("overlap_flags", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("similarity_keys", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("repeat_reason", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["shop_id"],
            ["shops.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_experiments_tenant_id"), "experiments", ["tenant_id"], unique=False)
    op.create_table(
        "ingestion_batches",
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("stream", sa.String(length=64), nullable=False),
        sa.Column("source_account_id", sa.UUID(), nullable=True),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("request_signature", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("range_start", sa.Date(), nullable=True),
        sa.Column("range_end", sa.Date(), nullable=True),
        sa.Column("raw_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("raw_uri", sa.String(length=500), nullable=True),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.Column("record_count", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("pagination_complete", sa.Boolean(), nullable=False),
        sa.Column("warnings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_account_id"],
            ["source_accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "request_hash", "fetched_at", name="uq_ingestion_batches"),
    )
    op.create_index(op.f("ix_ingestion_batches_tenant_id"), "ingestion_batches", ["tenant_id"], unique=False)
    op.create_table(
        "offers",
        sa.Column("shop_id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=True),
        sa.Column("offer_key", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["shop_id"],
            ["shops.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "shop_id", "offer_key", name="uq_offers"),
    )
    op.create_index(op.f("ix_offers_tenant_id"), "offers", ["tenant_id"], unique=False)
    op.create_table(
        "orders",
        sa.Column("source_account_id", sa.UUID(), nullable=False),
        sa.Column("shop_id", sa.UUID(), nullable=False),
        sa.Column("external_order_id", sa.String(length=64), nullable=False),
        sa.Column("created_at_source", sa.DateTime(timezone=True), nullable=False),
        sa.Column("confirmed_at_source", sa.DateTime(timezone=True), nullable=True),
        sa.Column("paid_at_source", sa.DateTime(timezone=True), nullable=True),
        sa.Column("business_date", sa.Date(), nullable=False),
        sa.Column("payment_kind", sa.String(length=16), nullable=False),
        sa.Column("payment_method", sa.String(length=64), nullable=True),
        sa.Column("current_status", sa.String(length=64), nullable=False),
        sa.Column("status_class", sa.String(length=16), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("gross_amount", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("products_amount", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("shipping_amount", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("discount_amount", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("is_valid", sa.Boolean(), nullable=False),
        sa.Column("is_test", sa.Boolean(), nullable=False),
        sa.Column("original_utm", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("customer_hash", sa.String(length=64), nullable=True),
        sa.Column("source_payload_hash", sa.String(length=64), nullable=True),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("matured_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["shop_id"],
            ["shops.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_account_id"],
            ["source_accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "source_account_id", "external_order_id", name="uq_orders"),
    )
    op.create_index(op.f("ix_orders_business_date"), "orders", ["business_date"], unique=False)
    op.create_index(op.f("ix_orders_shop_id"), "orders", ["shop_id"], unique=False)
    op.create_index(op.f("ix_orders_tenant_id"), "orders", ["tenant_id"], unique=False)
    op.create_table(
        "sync_checkpoints",
        sa.Column("source_account_id", sa.UUID(), nullable=False),
        sa.Column("stream", sa.String(length=64), nullable=False),
        sa.Column("cursor", sa.String(length=500), nullable=True),
        sa.Column("high_watermark", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("records_total", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_account_id"],
            ["source_accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "source_account_id", "stream", name="uq_sync_checkpoints"),
    )
    op.create_index(op.f("ix_sync_checkpoints_tenant_id"), "sync_checkpoints", ["tenant_id"], unique=False)
    op.create_table(
        "variants",
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("sku", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=True),
        sa.Column("attributes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("stock_qty", sa.Integer(), nullable=True),
        sa.Column("stock_as_of", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "product_id", "sku", name="uq_variants_sku"),
    )
    op.create_index(op.f("ix_variants_tenant_id"), "variants", ["tenant_id"], unique=False)
    op.create_table(
        "adsets",
        sa.Column("source_account_id", sa.UUID(), nullable=False),
        sa.Column("campaign_id", sa.UUID(), nullable=False),
        sa.Column("external_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("configured_status", sa.String(length=32), nullable=True),
        sa.Column("effective_status", sa.String(length=32), nullable=True),
        sa.Column("daily_budget", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("lifetime_budget", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("targeting", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_account_id"],
            ["source_accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "source_account_id", "external_id", name="uq_adsets"),
    )
    op.create_index(op.f("ix_adsets_tenant_id"), "adsets", ["tenant_id"], unique=False)
    op.create_table(
        "cost_versions",
        sa.Column("product_id", sa.UUID(), nullable=True),
        sa.Column("variant_id", sa.UUID(), nullable=True),
        sa.Column("shop_id", sa.UUID(), nullable=False),
        sa.Column("cost_type", sa.String(length=32), nullable=False),
        sa.Column("amount", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("tax_basis", sa.String(length=8), nullable=False),
        sa.Column("basis", sa.String(length=16), nullable=False),
        sa.Column("payment_kind", sa.String(length=16), nullable=True),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column("provenance", sa.String(length=200), nullable=False),
        sa.Column("recovery_rate", sa.Numeric(precision=6, scale=4), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["shop_id"],
            ["shops.id"],
        ),
        sa.ForeignKeyConstraint(
            ["variant_id"],
            ["variants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_cost_versions_tenant_id"), "cost_versions", ["tenant_id"], unique=False)
    op.create_table(
        "creatives",
        sa.Column("creative_key", sa.String(length=128), nullable=False),
        sa.Column("shop_id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=True),
        sa.Column("concept_id", sa.UUID(), nullable=True),
        sa.Column("asset_hash", sa.String(length=64), nullable=True),
        sa.Column("post_id", sa.String(length=128), nullable=True),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("hook", sa.Text(), nullable=True),
        sa.Column("angle", sa.String(length=200), nullable=True),
        sa.Column("format", sa.String(length=64), nullable=True),
        sa.Column("actor", sa.String(length=120), nullable=True),
        sa.Column("length_seconds", sa.Integer(), nullable=True),
        sa.Column("offer", sa.String(length=200), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("status_reason", sa.Text(), nullable=True),
        sa.Column("status_changed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("classification_confidence", sa.String(length=8), nullable=True),
        sa.Column("classification_evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("classification_version", sa.String(length=16), nullable=False),
        sa.Column("manual_override", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["concept_id"],
            ["concepts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["shop_id"],
            ["shops.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "creative_key", name="uq_creatives"),
    )
    op.create_index(op.f("ix_creatives_asset_hash"), "creatives", ["asset_hash"], unique=False)
    op.create_index(op.f("ix_creatives_post_id"), "creatives", ["post_id"], unique=False)
    op.create_index(op.f("ix_creatives_tenant_id"), "creatives", ["tenant_id"], unique=False)
    op.create_table(
        "decisions",
        sa.Column("recommendation_id", sa.UUID(), nullable=True),
        sa.Column("experiment_id", sa.UUID(), nullable=True),
        sa.Column("entity_ref", sa.String(length=200), nullable=False),
        sa.Column("entity_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("action_type", sa.String(length=32), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("rule_id", sa.String(length=64), nullable=True),
        sa.Column("state_before", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("state_after", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("data_as_of", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expected_effect", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("primary_metric", sa.String(length=64), nullable=False),
        sa.Column("target", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("risk", sa.Text(), nullable=True),
        sa.Column("test_budget_pln", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("loss_cap_pln", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("success_criterion", sa.Text(), nullable=True),
        sa.Column("horizon_hours", sa.Integer(), nullable=False),
        sa.Column("alternative", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("proposed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approved_by", sa.String(length=120), nullable=True),
        sa.Column("rejected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("executed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("verified_executed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("execution_kind", sa.String(length=16), nullable=True),
        sa.Column("outcome", sa.String(length=16), nullable=True),
        sa.Column("policy_version", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["experiment_id"],
            ["experiments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["recommendation_id"],
            ["recommendations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_decisions_entity_ref"), "decisions", ["entity_ref"], unique=False)
    op.create_index(op.f("ix_decisions_tenant_id"), "decisions", ["tenant_id"], unique=False)
    op.create_table(
        "entity_snapshots",
        sa.Column("entity_type", sa.String(length=16), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("valid_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("attributes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("attributes_hash", sa.String(length=64), nullable=False),
        sa.Column("batch_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["ingestion_batches.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id", "entity_type", "entity_id", "attributes_hash", "valid_at", name="uq_entity_snapshots"
        ),
    )
    op.create_index(op.f("ix_entity_snapshots_entity_id"), "entity_snapshots", ["entity_id"], unique=False)
    op.create_index(op.f("ix_entity_snapshots_tenant_id"), "entity_snapshots", ["tenant_id"], unique=False)
    op.create_table(
        "market_ads",
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("external_id", sa.String(length=128), nullable=False),
        sa.Column("brand", sa.String(length=200), nullable=False),
        sa.Column("basket", sa.String(length=16), nullable=True),
        sa.Column("media_hash", sa.String(length=64), nullable=True),
        sa.Column("media_ref", sa.String(length=500), nullable=True),
        sa.Column("first_seen", sa.Date(), nullable=True),
        sa.Column("last_seen", sa.Date(), nullable=True),
        sa.Column("countries", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("taxonomy", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("concept_id", sa.UUID(), nullable=True),
        sa.Column("transcript_available", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["concept_id"],
            ["concepts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "source", "external_id", name="uq_market_ads"),
    )
    op.create_index(op.f("ix_market_ads_media_hash"), "market_ads", ["media_hash"], unique=False)
    op.create_index(op.f("ix_market_ads_tenant_id"), "market_ads", ["tenant_id"], unique=False)
    op.create_table(
        "market_signals",
        sa.Column("concept_id", sa.UUID(), nullable=False),
        sa.Column("window_start", sa.Date(), nullable=False),
        sa.Column("window_end", sa.Date(), nullable=False),
        sa.Column("coverage", sa.String(length=16), nullable=False),
        sa.Column("components", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("trend_score", sa.Integer(), nullable=True),
        sa.Column("fit_to_product", sa.Numeric(precision=6, scale=4), nullable=True),
        sa.Column("novelty_for_us", sa.Numeric(precision=6, scale=4), nullable=True),
        sa.Column("source_observation_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["concept_id"],
            ["concepts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id", "concept_id", "window_start", "window_end", name="uq_market_signals"
        ),
    )
    op.create_index(op.f("ix_market_signals_tenant_id"), "market_signals", ["tenant_id"], unique=False)
    op.create_table(
        "offer_versions",
        sa.Column("offer_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("price_gross", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("reference_price_gross", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("reference_price_basis", sa.String(length=200), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("bundle", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("shipping_rule", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("landing_url", sa.Text(), nullable=True),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=True),
        sa.Column("valid_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column("inventory_rule", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["offer_id"],
            ["offers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "offer_id", "version", name="uq_offer_versions"),
    )
    op.create_index(op.f("ix_offer_versions_tenant_id"), "offer_versions", ["tenant_id"], unique=False)
    op.create_table(
        "order_items",
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("source_line_id", sa.String(length=64), nullable=False),
        sa.Column("external_product_id", sa.String(length=128), nullable=True),
        sa.Column("sku", sa.String(length=128), nullable=True),
        sa.Column("name", sa.String(length=300), nullable=True),
        sa.Column("variant_id", sa.UUID(), nullable=True),
        sa.Column("product_id", sa.UUID(), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("unit_price_gross", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("tax_rate", sa.Numeric(precision=6, scale=4), nullable=True),
        sa.Column("discount_amount", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("bundle_key", sa.String(length=64), nullable=True),
        sa.Column("returned_qty", sa.Integer(), nullable=False),
        sa.Column("recovered_qty", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["variant_id"],
            ["variants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "order_id", "source_line_id", name="uq_order_items"),
    )
    op.create_index(op.f("ix_order_items_tenant_id"), "order_items", ["tenant_id"], unique=False)
    op.create_table(
        "order_status_events",
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("source_event_hash", sa.String(length=64), nullable=False),
        sa.Column("event_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("before_status", sa.String(length=64), nullable=True),
        sa.Column("after_status", sa.String(length=64), nullable=False),
        sa.Column("after_class", sa.String(length=16), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "order_id", "source_event_hash", name="uq_order_status_events"),
    )
    op.create_index(
        op.f("ix_order_status_events_order_id"), "order_status_events", ["order_id"], unique=False
    )
    op.create_index(
        op.f("ix_order_status_events_tenant_id"), "order_status_events", ["tenant_id"], unique=False
    )
    op.create_table(
        "product_aliases",
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("external_product_id", sa.String(length=128), nullable=False),
        sa.Column("canonical_product_id", sa.UUID(), nullable=False),
        sa.Column("variant_id", sa.UUID(), nullable=True),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["canonical_product_id"],
            ["products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["variant_id"],
            ["variants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id", "source", "external_product_id", "valid_from", name="uq_product_aliases"
        ),
    )
    op.create_index(op.f("ix_product_aliases_tenant_id"), "product_aliases", ["tenant_id"], unique=False)
    op.create_table(
        "refunds",
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("external_id", sa.String(length=64), nullable=False),
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("amount", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("refund_type", sa.String(length=16), nullable=False),
        sa.Column("goods_recovered", sa.Boolean(), nullable=False),
        sa.Column("return_shipping_cost", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "source", "external_id", name="uq_refunds"),
    )
    op.create_index(op.f("ix_refunds_order_id"), "refunds", ["order_id"], unique=False)
    op.create_index(op.f("ix_refunds_tenant_id"), "refunds", ["tenant_id"], unique=False)
    op.create_table(
        "settlements",
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("external_id", sa.String(length=64), nullable=False),
        sa.Column("order_id", sa.UUID(), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("settlement_date", sa.Date(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("settlement_type", sa.String(length=16), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "source", "external_id", name="uq_settlements"),
    )
    op.create_index(op.f("ix_settlements_order_id"), "settlements", ["order_id"], unique=False)
    op.create_index(op.f("ix_settlements_tenant_id"), "settlements", ["tenant_id"], unique=False)
    op.create_table(
        "structure_changes",
        sa.Column("entity_type", sa.String(length=16), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("field", sa.String(length=64), nullable=False),
        sa.Column("before", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("after", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("observed_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("observed_to", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actor", sa.String(length=64), nullable=True),
        sa.Column("derivation", sa.String(length=32), nullable=False),
        sa.Column("batch_id", sa.UUID(), nullable=True),
        sa.Column("decision_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["ingestion_batches.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_structure_changes_entity_id"), "structure_changes", ["entity_id"], unique=False)
    op.create_index(op.f("ix_structure_changes_tenant_id"), "structure_changes", ["tenant_id"], unique=False)
    op.create_table(
        "action_requests",
        sa.Column("decision_id", sa.UUID(), nullable=False),
        sa.Column("target", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("operation", sa.String(length=32), nullable=False),
        sa.Column("before_state", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("after_state", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("precondition_hash", sa.String(length=64), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("policy_checks", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("approved_by", sa.String(length=120), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approval_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("executed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("verification", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["decision_id"],
            ["decisions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "idempotency_key", name="uq_action_requests_idem"),
    )
    op.create_index(op.f("ix_action_requests_tenant_id"), "action_requests", ["tenant_id"], unique=False)
    op.create_table(
        "ads",
        sa.Column("source_account_id", sa.UUID(), nullable=False),
        sa.Column("adset_id", sa.UUID(), nullable=False),
        sa.Column("external_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("configured_status", sa.String(length=32), nullable=True),
        sa.Column("effective_status", sa.String(length=32), nullable=True),
        sa.Column("post_id", sa.String(length=128), nullable=True),
        sa.Column("asset_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("asset_hash", sa.String(length=64), nullable=True),
        sa.Column("destination_url", sa.Text(), nullable=True),
        sa.Column("url_tags", sa.Text(), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["adset_id"],
            ["adsets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_account_id"],
            ["source_accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "source_account_id", "external_id", name="uq_ads"),
    )
    op.create_index(op.f("ix_ads_asset_hash"), "ads", ["asset_hash"], unique=False)
    op.create_index(op.f("ix_ads_post_id"), "ads", ["post_id"], unique=False)
    op.create_index(op.f("ix_ads_tenant_id"), "ads", ["tenant_id"], unique=False)
    op.create_table(
        "creative_variants",
        sa.Column("creative_id", sa.UUID(), nullable=False),
        sa.Column("parent_creative_id", sa.UUID(), nullable=True),
        sa.Column("variation_type", sa.String(length=32), nullable=False),
        sa.Column("classification_version", sa.String(length=16), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["creative_id"],
            ["creatives.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_creative_id"],
            ["creatives.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_creative_variants_tenant_id"), "creative_variants", ["tenant_id"], unique=False)
    op.create_table(
        "decision_evaluations",
        sa.Column("decision_id", sa.UUID(), nullable=False),
        sa.Column("horizon_hours", sa.Integer(), nullable=False),
        sa.Column("as_of", sa.DateTime(timezone=True), nullable=False),
        sa.Column("outcomes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("confounders", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("verdict", sa.String(length=16), nullable=False),
        sa.Column("observational_result", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["decision_id"],
            ["decisions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "decision_id", "horizon_hours", "as_of", name="uq_decision_evals"),
    )
    op.create_index(
        op.f("ix_decision_evaluations_decision_id"), "decision_evaluations", ["decision_id"], unique=False
    )
    op.create_index(
        op.f("ix_decision_evaluations_tenant_id"), "decision_evaluations", ["tenant_id"], unique=False
    )
    op.create_table(
        "market_observations",
        sa.Column("market_ad_id", sa.UUID(), nullable=False),
        sa.Column("observed_on", sa.Date(), nullable=False),
        sa.Column("coverage", sa.String(length=32), nullable=False),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("batch_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["ingestion_batches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["market_ad_id"],
            ["market_ads.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "market_ad_id", "observed_on", name="uq_market_observations"),
    )
    op.create_index(
        op.f("ix_market_observations_market_ad_id"), "market_observations", ["market_ad_id"], unique=False
    )
    op.create_index(
        op.f("ix_market_observations_tenant_id"), "market_observations", ["tenant_id"], unique=False
    )
    op.create_table(
        "order_costs",
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("order_item_id", sa.UUID(), nullable=True),
        sa.Column("cost_type", sa.String(length=32), nullable=False),
        sa.Column("amount", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("is_actual", sa.Boolean(), nullable=False),
        sa.Column("cost_version_id", sa.UUID(), nullable=True),
        sa.Column("recognition_date", sa.Date(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["cost_version_id"],
            ["cost_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.ForeignKeyConstraint(
            ["order_item_id"],
            ["order_items.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "order_id", "order_item_id", "cost_type", name="uq_order_costs"),
    )
    op.create_index(op.f("ix_order_costs_order_id"), "order_costs", ["order_id"], unique=False)
    op.create_index(op.f("ix_order_costs_tenant_id"), "order_costs", ["tenant_id"], unique=False)
    op.create_table(
        "ad_insights",
        sa.Column("ad_id", sa.UUID(), nullable=False),
        sa.Column("business_date", sa.Date(), nullable=False),
        sa.Column("hour", sa.Integer(), nullable=False),
        sa.Column("breakdown_key", sa.String(length=128), nullable=False),
        sa.Column("attribution_key", sa.String(length=128), nullable=False),
        sa.Column("action_report_time", sa.String(length=16), nullable=False),
        sa.Column("spend", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("impressions", sa.Integer(), nullable=False),
        sa.Column("reach", sa.Integer(), nullable=True),
        sa.Column("clicks_all", sa.Integer(), nullable=False),
        sa.Column("link_clicks", sa.Integer(), nullable=False),
        sa.Column("outbound_clicks", sa.Integer(), nullable=True),
        sa.Column("landing_page_views", sa.Integer(), nullable=True),
        sa.Column("add_to_cart", sa.Integer(), nullable=True),
        sa.Column("initiate_checkout", sa.Integer(), nullable=True),
        sa.Column("purchases", sa.Integer(), nullable=False),
        sa.Column("purchase_value", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("actions_raw", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("batch_id", sa.UUID(), nullable=True),
        sa.Column("as_of", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["ad_id"],
            ["ads.id"],
        ),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["ingestion_batches.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id",
            "ad_id",
            "business_date",
            "hour",
            "breakdown_key",
            "attribution_key",
            name="uq_ad_insights",
        ),
    )
    op.create_index(op.f("ix_ad_insights_ad_id"), "ad_insights", ["ad_id"], unique=False)
    op.create_index(op.f("ix_ad_insights_business_date"), "ad_insights", ["business_date"], unique=False)
    op.create_index(op.f("ix_ad_insights_tenant_id"), "ad_insights", ["tenant_id"], unique=False)
    op.create_table(
        "creative_placements",
        sa.Column("creative_id", sa.UUID(), nullable=False),
        sa.Column("ad_id", sa.UUID(), nullable=False),
        sa.Column("post_id", sa.String(length=128), nullable=True),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valid_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["ad_id"],
            ["ads.id"],
        ),
        sa.ForeignKeyConstraint(
            ["creative_id"],
            ["creatives.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "creative_id", "ad_id", "valid_from", name="uq_creative_placements"),
    )
    op.create_index(op.f("ix_creative_placements_ad_id"), "creative_placements", ["ad_id"], unique=False)
    op.create_index(
        op.f("ix_creative_placements_creative_id"), "creative_placements", ["creative_id"], unique=False
    )
    op.create_index(
        op.f("ix_creative_placements_tenant_id"), "creative_placements", ["tenant_id"], unique=False
    )
    op.create_table(
        "order_attribution",
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("source_account_id", sa.UUID(), nullable=True),
        sa.Column("campaign_id", sa.UUID(), nullable=True),
        sa.Column("adset_id", sa.UUID(), nullable=True),
        sa.Column("ad_id", sa.UUID(), nullable=True),
        sa.Column("level", sa.String(length=16), nullable=False),
        sa.Column("method", sa.String(length=32), nullable=False),
        sa.Column("confidence_class", sa.String(length=8), nullable=False),
        sa.Column("parsed_utm", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("parser_version", sa.String(length=16), nullable=False),
        sa.Column("model_version", sa.String(length=16), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["ad_id"],
            ["ads.id"],
        ),
        sa.ForeignKeyConstraint(
            ["adset_id"],
            ["adsets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_account_id"],
            ["source_accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "order_id", "model_version", name="uq_order_attribution"),
    )
    op.create_index(op.f("ix_order_attribution_order_id"), "order_attribution", ["order_id"], unique=False)
    op.create_index(op.f("ix_order_attribution_tenant_id"), "order_attribution", ["tenant_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_order_attribution_tenant_id"), table_name="order_attribution")
    op.drop_index(op.f("ix_order_attribution_order_id"), table_name="order_attribution")
    op.drop_table("order_attribution")
    op.drop_index(op.f("ix_creative_placements_tenant_id"), table_name="creative_placements")
    op.drop_index(op.f("ix_creative_placements_creative_id"), table_name="creative_placements")
    op.drop_index(op.f("ix_creative_placements_ad_id"), table_name="creative_placements")
    op.drop_table("creative_placements")
    op.drop_index(op.f("ix_ad_insights_tenant_id"), table_name="ad_insights")
    op.drop_index(op.f("ix_ad_insights_business_date"), table_name="ad_insights")
    op.drop_index(op.f("ix_ad_insights_ad_id"), table_name="ad_insights")
    op.drop_table("ad_insights")
    op.drop_index(op.f("ix_order_costs_tenant_id"), table_name="order_costs")
    op.drop_index(op.f("ix_order_costs_order_id"), table_name="order_costs")
    op.drop_table("order_costs")
    op.drop_index(op.f("ix_market_observations_tenant_id"), table_name="market_observations")
    op.drop_index(op.f("ix_market_observations_market_ad_id"), table_name="market_observations")
    op.drop_table("market_observations")
    op.drop_index(op.f("ix_decision_evaluations_tenant_id"), table_name="decision_evaluations")
    op.drop_index(op.f("ix_decision_evaluations_decision_id"), table_name="decision_evaluations")
    op.drop_table("decision_evaluations")
    op.drop_index(op.f("ix_creative_variants_tenant_id"), table_name="creative_variants")
    op.drop_table("creative_variants")
    op.drop_index(op.f("ix_ads_tenant_id"), table_name="ads")
    op.drop_index(op.f("ix_ads_post_id"), table_name="ads")
    op.drop_index(op.f("ix_ads_asset_hash"), table_name="ads")
    op.drop_table("ads")
    op.drop_index(op.f("ix_action_requests_tenant_id"), table_name="action_requests")
    op.drop_table("action_requests")
    op.drop_index(op.f("ix_structure_changes_tenant_id"), table_name="structure_changes")
    op.drop_index(op.f("ix_structure_changes_entity_id"), table_name="structure_changes")
    op.drop_table("structure_changes")
    op.drop_index(op.f("ix_settlements_tenant_id"), table_name="settlements")
    op.drop_index(op.f("ix_settlements_order_id"), table_name="settlements")
    op.drop_table("settlements")
    op.drop_index(op.f("ix_refunds_tenant_id"), table_name="refunds")
    op.drop_index(op.f("ix_refunds_order_id"), table_name="refunds")
    op.drop_table("refunds")
    op.drop_index(op.f("ix_product_aliases_tenant_id"), table_name="product_aliases")
    op.drop_table("product_aliases")
    op.drop_index(op.f("ix_order_status_events_tenant_id"), table_name="order_status_events")
    op.drop_index(op.f("ix_order_status_events_order_id"), table_name="order_status_events")
    op.drop_table("order_status_events")
    op.drop_index(op.f("ix_order_items_tenant_id"), table_name="order_items")
    op.drop_table("order_items")
    op.drop_index(op.f("ix_offer_versions_tenant_id"), table_name="offer_versions")
    op.drop_table("offer_versions")
    op.drop_index(op.f("ix_market_signals_tenant_id"), table_name="market_signals")
    op.drop_table("market_signals")
    op.drop_index(op.f("ix_market_ads_tenant_id"), table_name="market_ads")
    op.drop_index(op.f("ix_market_ads_media_hash"), table_name="market_ads")
    op.drop_table("market_ads")
    op.drop_index(op.f("ix_entity_snapshots_tenant_id"), table_name="entity_snapshots")
    op.drop_index(op.f("ix_entity_snapshots_entity_id"), table_name="entity_snapshots")
    op.drop_table("entity_snapshots")
    op.drop_index(op.f("ix_decisions_tenant_id"), table_name="decisions")
    op.drop_index(op.f("ix_decisions_entity_ref"), table_name="decisions")
    op.drop_table("decisions")
    op.drop_index(op.f("ix_creatives_tenant_id"), table_name="creatives")
    op.drop_index(op.f("ix_creatives_post_id"), table_name="creatives")
    op.drop_index(op.f("ix_creatives_asset_hash"), table_name="creatives")
    op.drop_table("creatives")
    op.drop_index(op.f("ix_cost_versions_tenant_id"), table_name="cost_versions")
    op.drop_table("cost_versions")
    op.drop_index(op.f("ix_adsets_tenant_id"), table_name="adsets")
    op.drop_table("adsets")
    op.drop_index(op.f("ix_variants_tenant_id"), table_name="variants")
    op.drop_table("variants")
    op.drop_index(op.f("ix_sync_checkpoints_tenant_id"), table_name="sync_checkpoints")
    op.drop_table("sync_checkpoints")
    op.drop_index(op.f("ix_orders_tenant_id"), table_name="orders")
    op.drop_index(op.f("ix_orders_shop_id"), table_name="orders")
    op.drop_index(op.f("ix_orders_business_date"), table_name="orders")
    op.drop_table("orders")
    op.drop_index(op.f("ix_offers_tenant_id"), table_name="offers")
    op.drop_table("offers")
    op.drop_index(op.f("ix_ingestion_batches_tenant_id"), table_name="ingestion_batches")
    op.drop_table("ingestion_batches")
    op.drop_index(op.f("ix_experiments_tenant_id"), table_name="experiments")
    op.drop_table("experiments")
    op.drop_index(op.f("ix_concepts_tenant_id"), table_name="concepts")
    op.drop_table("concepts")
    op.drop_index(op.f("ix_campaigns_tenant_id"), table_name="campaigns")
    op.drop_table("campaigns")
    op.drop_index(op.f("ix_source_accounts_tenant_id"), table_name="source_accounts")
    op.drop_table("source_accounts")
    op.drop_index(op.f("ix_recommendations_tenant_id"), table_name="recommendations")
    op.drop_index(op.f("ix_recommendations_entity_ref"), table_name="recommendations")
    op.drop_table("recommendations")
    op.drop_index(op.f("ix_products_tenant_id"), table_name="products")
    op.drop_table("products")
    op.drop_index(op.f("ix_notification_outbox_tenant_id"), table_name="notification_outbox")
    op.drop_table("notification_outbox")
    op.drop_index(op.f("ix_historical_observations_tenant_id"), table_name="historical_observations")
    op.drop_table("historical_observations")
    op.drop_index(op.f("ix_shops_tenant_id"), table_name="shops")
    op.drop_table("shops")
    op.drop_index(op.f("ix_reports_tenant_id"), table_name="reports")
    op.drop_table("reports")
    op.drop_index(op.f("ix_policy_snapshots_tenant_id"), table_name="policy_snapshots")
    op.drop_table("policy_snapshots")
    op.drop_index(op.f("ix_job_runs_tenant_id"), table_name="job_runs")
    op.drop_index(op.f("ix_job_runs_status"), table_name="job_runs")
    op.drop_index(op.f("ix_job_runs_scheduled_for"), table_name="job_runs")
    op.drop_index(op.f("ix_job_runs_job_name"), table_name="job_runs")
    op.drop_table("job_runs")
    op.drop_index(op.f("ix_data_quality_issues_tenant_id"), table_name="data_quality_issues")
    op.drop_index(op.f("ix_data_quality_issues_dedupe_key"), table_name="data_quality_issues")
    op.drop_table("data_quality_issues")
    op.drop_index(op.f("ix_daily_metrics_tenant_id"), table_name="daily_metrics")
    op.drop_index("ix_daily_metrics_lookup", table_name="daily_metrics")
    op.drop_table("daily_metrics")
    op.drop_index(op.f("ix_connector_capabilities_tenant_id"), table_name="connector_capabilities")
    op.drop_table("connector_capabilities")
    op.drop_index(op.f("ix_cohort_metrics_tenant_id"), table_name="cohort_metrics")
    op.drop_index(op.f("ix_cohort_metrics_cohort_date"), table_name="cohort_metrics")
    op.drop_table("cohort_metrics")
    op.drop_index(op.f("ix_audit_events_tenant_id"), table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_index(op.f("ix_alerts_tenant_id"), table_name="alerts")
    op.drop_table("alerts")
    # ### end Alembic commands ###
